# Generated by Django 3.2 on 2021-05-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalRoud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge', models.CharField(max_length=5)),
                ('steam', models.CharField(max_length=4)),
                ('distance', models.IntegerField()),
            ],
        ),
    ]
